server:
  port: 8360

spring:
  application:
    name: noa-service

spring.data.mongodb:
  authentication-database: minalogin
  host: 127.0.0.1
  port: 27017
  database: MINALogin2
  username: minalogin
  password: minalogin

jwt:
  secret: noa@=9!
  expiration-second: 604800